### ISSUE TITLE
Cambiar nombre del archivo apk

### ISSUE THREAD

**Issue by Pablohn26** [Webierta/tarifa_luz#2]
Actualmente se llama app-release.apk

Creo que es mejor idea llamarlo tarifa-luz.apk o algo que sea más informativo.

**Comment by Webierta** [comment]
Hecho! A partir de la próxima versión el archivo apk dejará de llamarse **app-release.apk** y se llamará **TarifaLuz-[version].apk**. Por ejemplo, en en esta versión sería: **TarifaLuz-3.2.0.apk**

Gracias por la sugerencia.

Por cierto, para quien le de un aviso diciendo algo así como que "Es posible que el archivo sea dañino...", comentar que ese aviso puede salir dependiendo de la configuración del sistema android y concretamente del navegador que hace la descarga o del gestor de archivos que se utilice y los permisos concedidos a estas aplicaciones.

Una captura analizando el archivo apk (aunque nada mejor que la seguridad del código abierto):

![apk](https://github.com/Webierta/tarifa_luz/assets/3810289/5162179d-2ecd-4424-bc1c-9c0e91ed0224)
