### ISSUE TITLE
Permitir configurar un límite para los datos archivados

### ISSUE THREAD

**Issue by wuniversales** [Webierta/tarifa_luz#6]
Buenas, Se me acaba de ocurrir la idea, espero que os guste!!
Como dice el título, la idea es permitir en la configuracion poner un limite de datos archivados, borrar el archivo mas viejo y mantener los recientes.
Me gustaría poner el limite a 7 archivos o algo así. (Tal vez permitir elegir el limite al usuario dando la opcion de permitir dejarlo sin limite que es como esta ahora)
La finalidad es auto-limpiar los datos tras muchos usos de la aplicación.
Saludos

**Comment by Webierta** [comment]
Bien, me parece buena idea, me voy poniendo a ello...

Gracias por la sugerencia

**Comment by Webierta** [comment]
Añadido en versión 4.0.1. Agradecería testeo de esta nueva función. Un saludo

**Comment by wuniversales** [comment]
Parece que funciona bien! Saludos
